### ISSUE TITLE
可以分享笔记吗？

### ISSUE THREAD

**Issue by MobiusDai** [Iamctb/NoteSchedule#1]
请问这个APP可以分享笔记啥的吗？

**Comment by Iamctb** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是陈太兵，你的信息已收到，感谢来电。

**Comment by Iamctb** [comment]
这是一款不联网的应用，所以没有做分享这个功能！

而且，笔记分享这个需求如果真的要做的话，好像比较麻烦：
如果分享到微信，好像微信分享的API对个人开发者不太友好；
如果做APP内的分享，就只能搭服务器保存用户信息，这样就涉及到用户信息安全了。

朋友可以去实践一下，到时分享给我一下，我其实也非常希望能实现分享功能。

**Comment by Iamctb** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是陈太兵，你的信息已收到，感谢来电。
